/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package filedemultiplexer;

import com.sun.java.swing.plaf.nimbus.SliderSliderThumbPainter;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Alp Sayin
 */
public class MainForm extends javax.swing.JFrame
{

    /**
     * Creates new form MainForm
     */
    private long deltaTime;
    public MainForm()
    {
        initComponents();
        this.deltaTime=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputFileChooser = new javax.swing.JFileChooser();
        outputFileChooser = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        outputPatternField = new javax.swing.JTextField();
        outputExtensionField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inputFilenameField = new javax.swing.JTextField();
        inputBrowseButton = new javax.swing.JButton();
        demuxButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        demuxSlider = new javax.swing.JSlider();
        sliderDisplay = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        readBufferSlider = new javax.swing.JSlider();
        writeBufferSlider = new javax.swing.JSlider();
        readBufferLabel = new javax.swing.JLabel();
        writeBufferLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        outputLocationField = new javax.swing.JTextField();
        outputBrowseButton = new javax.swing.JButton();

        outputFileChooser.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        outputFileChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("File Demultiplexer");
        setLocationByPlatform(true);
        setResizable(false);

        jLabel1.setText("Output File Name Pattern:");

        jLabel2.setText("Output File Name Extension:");

        outputPatternField.setText("Channel");

        outputExtensionField.setText("misl");

        jLabel3.setText("Input File:");

        inputFilenameField.setEditable(false);
        inputFilenameField.setText("[none]");

        inputBrowseButton.setText("Browse");
        inputBrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBrowseButtonActionPerformed(evt);
            }
        });

        demuxButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        demuxButton.setText("Demux");
        demuxButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                demuxButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Output File Count:");

        demuxSlider.setMajorTickSpacing(2);
        demuxSlider.setMaximum(8);
        demuxSlider.setMinimum(2);
        demuxSlider.setMinorTickSpacing(1);
        demuxSlider.setEnabled(false);
        demuxSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                demuxSliderStateChanged(evt);
            }
        });

        sliderDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sliderDisplay.setText("8");

        jLabel5.setText("Read Buffer Size (KB):");

        jLabel6.setText("Write Buffer Size (KB):");

        readBufferSlider.setMajorTickSpacing(1024);
        readBufferSlider.setMaximum(262144);
        readBufferSlider.setMinimum(1);
        readBufferSlider.setMinorTickSpacing(512);
        readBufferSlider.setValue(4096);
        readBufferSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                readBufferSliderStateChanged(evt);
            }
        });

        writeBufferSlider.setMajorTickSpacing(1024);
        writeBufferSlider.setMaximum(32768);
        writeBufferSlider.setMinimum(1);
        writeBufferSlider.setMinorTickSpacing(512);
        writeBufferSlider.setValue(512);
        writeBufferSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                writeBufferSliderStateChanged(evt);
            }
        });

        readBufferLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        readBufferLabel.setText("4096");

        writeBufferLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        writeBufferLabel.setText("512");

        jLabel7.setText("Output Location:");

        outputLocationField.setEditable(false);
        outputLocationField.setText(new File(".").getAbsolutePath());

        outputBrowseButton.setText("Browse");
        outputBrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputBrowseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(outputPatternField)
                            .addComponent(outputExtensionField)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(25, 25, 25)
                        .addComponent(demuxSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sliderDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(demuxButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(outputLocationField)
                            .addComponent(inputFilenameField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(outputBrowseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputBrowseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(writeBufferSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(readBufferSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(writeBufferLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(readBufferLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(outputPatternField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(outputExtensionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inputFilenameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputBrowseButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(outputLocationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputBrowseButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(demuxSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(demuxButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sliderDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(readBufferSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(readBufferLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(writeBufferLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(writeBufferSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputBrowseButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_inputBrowseButtonActionPerformed
    {//GEN-HEADEREND:event_inputBrowseButtonActionPerformed
        int retVal = inputFileChooser.showOpenDialog(this);
        if(retVal == JFileChooser.APPROVE_OPTION)
        {
            inputFilenameField.setText(inputFileChooser.getSelectedFile().getAbsolutePath());
            outputLocationField.setText(inputFileChooser.getSelectedFile().getParentFile().getAbsolutePath());
        }
    }//GEN-LAST:event_inputBrowseButtonActionPerformed

    private void demuxButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_demuxButtonActionPerformed
    {//GEN-HEADEREND:event_demuxButtonActionPerformed
        File inputFile = new File(inputFilenameField.getText());
        if(!inputFile.exists())
        {
            JOptionPane.showMessageDialog(this, "The input file doesn't exist: "+inputFilenameField.getText(), "File Doesn't Exist!", JOptionPane.ERROR_MESSAGE);
        }      
        else
        {
            FileDemultiplexer fdm = new FileDemultiplexer(inputFilenameField.getText(), outputPatternField.getText(), outputExtensionField.getText(), outputLocationField.getText(), demuxSlider.getValue(), readBufferSlider.getValue(), writeBufferSlider.getValue());
            try
            {
                deltaTime = System.currentTimeMillis();
                fdm.demultiplex();
                deltaTime = System.currentTimeMillis() - deltaTime;
                long deltaTimeMinutes = (deltaTime/1000)/60;
                long deltaTimeSeconds = (deltaTime/1000)%60;
                long deltaTimeMillis = deltaTime%1000;
                JOptionPane.showMessageDialog(this, "File demultiplexing is completed in "+deltaTimeMinutes+" minutes, "+deltaTimeSeconds+" seconds, "+deltaTimeMillis+" milliseconds.", "Demux Completed",  JOptionPane.INFORMATION_MESSAGE);
            }
            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(this, ex.getMessage(), ex.getCause().toString(), JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_demuxButtonActionPerformed

    private void demuxSliderStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_demuxSliderStateChanged
    {//GEN-HEADEREND:event_demuxSliderStateChanged
        sliderDisplay.setText(String.valueOf(demuxSlider.getValue()));
    }//GEN-LAST:event_demuxSliderStateChanged

    private void writeBufferSliderStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_writeBufferSliderStateChanged
    {//GEN-HEADEREND:event_writeBufferSliderStateChanged
        writeBufferLabel.setText(String.valueOf(writeBufferSlider.getValue()));
    }//GEN-LAST:event_writeBufferSliderStateChanged

    private void readBufferSliderStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_readBufferSliderStateChanged
    {//GEN-HEADEREND:event_readBufferSliderStateChanged
        readBufferLabel.setText(String.valueOf(readBufferSlider.getValue()));
    }//GEN-LAST:event_readBufferSliderStateChanged

    private void outputBrowseButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_outputBrowseButtonActionPerformed
    {//GEN-HEADEREND:event_outputBrowseButtonActionPerformed
        int retVal = outputFileChooser.showSaveDialog(this);
        if(retVal == JFileChooser.APPROVE_OPTION)
        {
            outputLocationField.setText(outputFileChooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_outputBrowseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable()
        {

            public void run()
            {
                new MainForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton demuxButton;
    private javax.swing.JSlider demuxSlider;
    private javax.swing.JButton inputBrowseButton;
    private javax.swing.JFileChooser inputFileChooser;
    private javax.swing.JTextField inputFilenameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton outputBrowseButton;
    private javax.swing.JTextField outputExtensionField;
    private javax.swing.JFileChooser outputFileChooser;
    private javax.swing.JTextField outputLocationField;
    private javax.swing.JTextField outputPatternField;
    private javax.swing.JLabel readBufferLabel;
    private javax.swing.JSlider readBufferSlider;
    private javax.swing.JLabel sliderDisplay;
    private javax.swing.JLabel writeBufferLabel;
    private javax.swing.JSlider writeBufferSlider;
    // End of variables declaration//GEN-END:variables
}
